import type { Client, Invoice, Organization } from "@invoice-generator/types";
export const organization: Organization = {
  id: "org_1",
  name: "Acme Studio",
  address: "12, Indiranagar",
  state: "Karnataka",
  country: "India",
  gstNumber: "29ABCDE1234F1Z5",
  logoUrl: null,
  signatureUrl: null,
  contactDetails: "+91 98765 43210",
  invoiceNumberPrefix: "ACME/24-25/",
  invoiceNumberCurrentSeq: 128,
  bankDetails: "HDFC Bank • 001234567890",
  createdAt: "2024-04-01",
};
export const clients: Client[] = [
  {
    id: "c1",
    orgId: "org_1",
    name: "Saffron Foods Pvt. Ltd.",
    gstNumber: "27AABCS1429B1ZK",
    address: "Bandra West, Mumbai",
    state: "Maharashtra",
    country: "India",
    contactDetails: "+91 99887 22110",
    email: "accounts@saffronfoods.in",
    isDeleted: false,
    createdAt: "2024-05-10",
  },
  {
    id: "c2",
    orgId: "org_1",
    name: "Nandi Technologies",
    gstNumber: "29AABCN8745C1ZJ",
    address: "Koramangala, Bengaluru",
    state: "Karnataka",
    country: "India",
    contactDetails: "+91 98800 66554",
    email: "hello@nandi.tech",
    isDeleted: false,
    createdAt: "2024-06-02",
  },
  {
    id: "c3",
    orgId: "org_1",
    name: "Mango Tree Retail",
    gstNumber: null,
    address: "Pune, Maharashtra",
    state: "Maharashtra",
    country: "India",
    contactDetails: "+91 90000 11223",
    email: "billing@mangotree.in",
    isDeleted: false,
    createdAt: "2024-07-19",
  },
];
export const invoices: Invoice[] = [
  {
    id: "i1",
    orgId: "org_1",
    clientId: "c1",
    invoiceNumber: "ACME/24-25/0128",
    status: "active",
    isGstInvoice: true,
    gstSplitType: "igst",
    amountPaid: 0,
    subtotal: 24000,
    total: 28320,
    signatureUrl: null,
    isDeleted: false,
    createdAt: "2025-01-24",
    updatedAt: "2025-01-24",
    items: [
      {
        id: "it1",
        itemName: "Brand identity design",
        hsnSacCode: "998391",
        quantity: 1,
        gstPercentage: 18,
        rate: 24000,
        total: 28320,
      },
    ],
  },
  {
    id: "i2",
    orgId: "org_1",
    clientId: "c2",
    invoiceNumber: "ACME/24-25/0127",
    status: "paid",
    isGstInvoice: true,
    gstSplitType: "cgst_sgst",
    amountPaid: 17700,
    subtotal: 15000,
    total: 17700,
    signatureUrl: null,
    isDeleted: false,
    createdAt: "2025-01-18",
    updatedAt: "2025-01-20",
    items: [
      {
        id: "it2",
        itemName: "Website maintenance",
        hsnSacCode: "998314",
        quantity: 1,
        gstPercentage: 18,
        rate: 15000,
        total: 17700,
      },
    ],
  },
  {
    id: "i3",
    orgId: "org_1",
    clientId: "c3",
    invoiceNumber: "ACME/24-25/0126",
    status: "draft",
    isGstInvoice: false,
    gstSplitType: "none",
    amountPaid: 0,
    subtotal: 8500,
    total: 8500,
    signatureUrl: null,
    isDeleted: false,
    createdAt: "2025-01-12",
    updatedAt: "2025-01-12",
    items: [
      {
        id: "it3",
        itemName: "Product photography",
        hsnSacCode: "",
        quantity: 1,
        gstPercentage: null,
        rate: 8500,
        total: 8500,
      },
    ],
  },
  {
    id: "i4",
    orgId: "org_1",
    clientId: "c1",
    invoiceNumber: "ACME/24-25/0125",
    status: "partially_paid",
    isGstInvoice: true,
    gstSplitType: "igst",
    amountPaid: 5900,
    subtotal: 10000,
    total: 11800,
    signatureUrl: null,
    isDeleted: false,
    createdAt: "2025-01-05",
    updatedAt: "2025-01-10",
    items: [
      {
        id: "it4",
        itemName: "Packaging illustrations",
        hsnSacCode: "998391",
        quantity: 1,
        gstPercentage: 18,
        rate: 10000,
        total: 11800,
      },
    ],
  },
];
export const getClient = (id: string): Client =>
  clients.find((client) => client.id === id) ?? clients[0]!;
export const money = (amount: number): string =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
